apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-storage
provisioner: nfs-client    
parameters:
  archiveOnDelete: "true"  
mountOptions: 
  - hard                   
  - nfsvers=4              #指定NFS版本