---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
spec:
  selector:
    app: app-registry
  ports:
    - name: http
      port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default   
spec:
  selector:
    matchLabels:
      app: app-registry
  template:
    metadata:
      labels:
        app: app-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_ADDR
          value: '0.0.0.0:5000'
        - name: REGISTRY_HTTP_HOST
          value: 'http://registry.sillycat.net'
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-data
        - mountPath: /etc/docker/registry/config.yml
          name: registry-config
      volumes:
      - name: registry-data
        hostPath:
          path: /opt/registry/data
      - name: registry-config
        hostPath:
          path: /opt/registry/config/config.yml
      nodeSelector:
        IngressProxy: "true"