---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
spec:
  selector:
    app: app-registry
  ports:
    - name: http
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: default
spec:
  selector:
    app: app-registry
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default   
spec:
  selector:
    matchLabels:
      app: app-registry
  template:
    metadata:
      labels:
        app: app-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_ADDR
          value: '0.0.0.0:5000'
        - name: REGISTRY_HTTP_HOST
          value: 'http://registry.sillycat.net'
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-data
        - mountPath: /etc/docker/registry/config.yml
          name: registry-config
      - name: registry-ui
        image: joxit/docker-registry-ui:static
        env:
        - name: REGISTRY_TITLE
          value: "Sillycat Registry"
        - name: REGISTRY_URL
          value: "http://localhost:5000"
        - name: NGINX_PROXY_HEADER_X_Forwarded_For
          value: "$$proxy_add_x_forwarded_for"
        - name: NGINX_PROXY_HEADER_Authorization
          value: "Basic YWRtaW46MTIzNDU2"
        - name: DELETE_IMAGES
          value: "true"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/.env
          name: nginx-config
      volumes:
      - name: registry-data
        hostPath:
          path: /opt/registry/data
      - name: registry-config
        hostPath:
          path: /opt/registry/config/config.yml
      - name: nginx-config
        hostPath:
          path: /opt/registry/config/nginx.env
      nodeSelector:
        IngressProxy: "true"