apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-sentinel-pv0
  namespace: default
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    path: /opt/k8s-nfs/redis/sentinel0
    server: centos7-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-sentinel-pv1
  namespace: default
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    path: /opt/k8s-nfs/redis/sentinel1
    server: centos7-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-sentinel-pv2
  namespace: default
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    path: /opt/k8s-nfs/redis/sentinel2
    server: centos7-master
