apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-sentinel-0
  namespace: database
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    # real share directory
    path: /data/nfs/redis-cluster/0
    # nfs real ip
    server: nfs ip

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-sentinel-1
  namespace: database
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    # real share directory
    path: /data/nfs/redis-cluster/1
    # nfs real ip
    server: nfs ip

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-sentinel-2
  namespace: database
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    # real share directory
    path: /data/nfs/redis-cluster/2
    # nfs real ip
    server: nfs ip
