apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-sentinel-pv0
  namespace: default
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    path: /opt/k8s/redis/sentinel0
    server: centos7-leader

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-sentinel-pv1
  namespace: default
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    path: /opt/k8s/redis/sentinel1
    server: centos7-leader

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-sentinel-2
  namespace: database
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-sentinel-storage-class"
  nfs:
    path: /opt/k8s/redis/sentinel2
    server: centos7-leader
