apiVersion: v1
kind: PersistentVolume
metadata:
  name: "prometheus-pv"
  labels:
    name: prometheus-pv
    release: stable
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/k8s-nfs/prometheus/pv
    server: centos7-master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: prometheus-pv
      release: stable