kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: nginxweb-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: basic-auth
    
spec:
  rules:
    - host: nginxweb.sillycat.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: nginx
              servicePort: 80
