apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: redis-data-airflow-redis-master-0
  nfs:
    server: centos7-leader
    path: "/opt/k8s/redis/master"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-slave
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: redis-data-airflow-redis-slave-0
  nfs:
    server: centos7-leader
    path: "/opt/k8s/redis/slave"