apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.8
          args:
            - --log.level=DEBUG
            - --api
            - --api.insecure
            - --entrypoints.web.address=:80
            - --entrypoints.redis.address=:6379/TCP
            - --entrypoints.sentinel.address=:26379/TCP
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: admin
              containerPort: 8080
              hostPort: 8080
            - name: redis
              containerPort: 6379
              hostPort: 6379
            - name: sentinel
              containerPort: 26379
              hostPort: 26379
      nodeSelector:
        IngressProxy: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - name: web
      port: 80
    - name: admin
      port: 8080
    - name: redis
      port: 6379
      protocol: TCP
    - name: sentinel
      port: 26379
      protocol: TCP
  selector:
    app: traefik